### ISSUE TITLE
This repository seem to not have gitignore file.

### ISSUE THREAD

**Issue by kittiu** [OCA/account-budgeting#28]
I create an PR, and it got all the .pyc

**Comment by pedrobaeza** [comment]
Not all repositories are properly initialized. Get the template of .gitignore in maintainer quality tools repo.

**Comment by kittiu** [comment]
I added it in the PR https://github.com/OCA/account-budgeting/pull/29

**Comment by pedrobaeza** [comment]
I prefer to be added in a separate PR for being fast-tracked, and all the upcoming PRs benefit from it.

**Comment by kittiu** [comment]
Here you go! https://github.com/OCA/account-budgeting/pull/30
