### ISSUE TITLE
Invoicing -> Accounting - where is it ?

### ISSUE THREAD

**Issue by humanitiesNerd** [OCA/account-budgeting#75]
Installed this module in Odoo 16

According to the "Installed Features" of the module, one of the entry points in the GUI is 

Invoicing -> Accounting -> Management -> Budgets

But I can't find

Invoicing -> Accounting 

Any hint appreciated
Thanks in advance

**Comment by Saran440** [comment]
Hi, @humanitiesNerd Menu Accounting is hide, you must have permission `show full accounting` will see menu.
1. Open dev mode
2. Go to Settings > Users & Companies > Groups > search `Show Full Accounting Features` and add user
3. Refresh browser and check again.

**Comment by max3903** [comment]
https://odoo-community.org/shop/account-missing-menus-saxon-accounting-10561
